services:
  js-ping-node:
    image: ghcr.io/yushare999-tech/js-ping-node:${PING_VERSION:-latest}
    container_name: js-ping-node
    network_mode: "host"
    volumes:
      - ${HOST_REAL_PATH:-.}/config.yaml:/app/config.yaml
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/run/tailscale/tailscaled.sock:/var/run/tailscale/tailscaled.sock:ro
      - ${HOST_REAL_PATH:-.}:/host_dir
      - /etc/machine-id:/etc/machine-id:ro
      - /usr/local/bin:/host_bin
    environment:
      - HOST_DIR=/host_dir
      - HOST_REAL_PATH=${HOST_REAL_PATH}
      - CONTAINER_NAME=js-ping-node
    restart: always
