services:
  js-ping-node:
    image: ghcr.io/yushare999-tech/js-ping-node:latest
    container_name: js-ping-node
    network_mode: "host"
    volumes:
      - ./config.yaml:/app/config.yaml
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/host_dir
      - /etc/machine-id:/etc/machine-id:ro
    environment:
      - HOST_DIR=/host_dir
      - HOST_REAL_PATH=${HOST_REAL_PATH}
      - CONTAINER_NAME=js-ping-node
    restart: always
